import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, readFileSync, rmSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createHash, randomBytes } from "node:crypto";
import { homedir } from "node:os";
import { join } from "node:path";

// Build provenance baked into the bundle so the plugin can tell a real release
// from a local/custom build (see src/buildInfo.ts). `git` may be unavailable
// (e.g. building from a source tarball) — degrade to null, never fail the build.
// Captured once at config load: production builds are one-shot so this is exact;
// in `--watch` (dev) it reflects the state when the watcher started, which is
// fine for a dev provenance banner.
function gitOut(args) {
	try {
		return execFileSync("git", args, { encoding: "utf8" }).trim() || null;
	} catch {
		return null;
	}
}
const buildInfo = {
	commit: gitOut(["rev-parse", "--short", "HEAD"]),
	branch: gitOut(["rev-parse", "--abbrev-ref", "HEAD"]),
	buildDate: new Date().toISOString().slice(0, 10),
	// release.yml sets MC_RELEASE=1 for tagged release builds; every other build
	// (local deploy, plain `npm run build`) is a custom build.
	isRelease: process.env.MC_RELEASE === "1",
};

// The local-VAD engine needs the fvad WASM binary sitting next to main.js at
// runtime (the loader reads it from the plugin dir and hands the bytes to the
// emscripten glue). The glue itself is bundled into main.js; only the binary
// ships as a separate asset. Keep this in sync with deploy-local.mjs and
// release.yml.
const FVAD_WASM_SRC = "node_modules/@echogarden/fvad-wasm/fvad.wasm";
const FVAD_WASM_DEST = "fvad.wasm";
function copyFvadWasm() {
	if (existsSync(FVAD_WASM_SRC)) {
		copyFileSync(FVAD_WASM_SRC, FVAD_WASM_DEST);
	} else {
		// Missing binary is not fatal: diarization window detection falls back to
		// the recorder's RMS speech.json (then to no filtering). Remove any stale
		// copy so we don't ship a mismatched asset.
		rmSync(FVAD_WASM_DEST, { force: true });
	}
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// -- Credentials plugin -------------------------------------------------------
// XOR-encodes the Google OAuth credentials at build time so they don't appear
// as plain strings in main.js. Both the ciphertext and the key are baked in —
// this is obfuscation, not encryption — but it stops naive grep/strings from
// surfacing them. A fresh random key is generated on every build.
//
// Credential sources (first non-empty wins):
//   1. GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET env vars   (CI/release.yml)
//   2. ~/.config/obsidian-meeting-copilot/credentials.json (local dev)
//   3. Empty arrays → bundled auth disabled (CI lint/test builds are fine)

function loadBuildCredentials() {
	let id = process.env.GOOGLE_CLIENT_ID ?? "";
	let secret = process.env.GOOGLE_CLIENT_SECRET ?? "";
	if (!id || !secret) {
		const local = join(homedir(), ".config", "obsidian-meeting-copilot", "credentials.json");
		if (existsSync(local)) {
			try {
				const cfg = JSON.parse(readFileSync(local, "utf8"));
				id = id || cfg.googleClientId || "";
				secret = secret || cfg.googleClientSecret || "";
			} catch { /* ignore */ }
		}
	}
	return { id, secret };
}

function xorEncode(str, key) {
	const bytes = Buffer.from(str, "utf8");
	return Array.from(bytes, (b, i) => b ^ key[i % key.length]);
}

function credentialsPlugin() {
	return {
		name: "mc-credentials",
		setup(build) {
			const { id, secret } = loadBuildCredentials();
			if (!id || !secret) {
				console.warn("mc-credentials: no credentials found — bundled OAuth will be disabled");
			}
			const key = Array.from(randomBytes(32));
			build.initialOptions.define = {
				...(build.initialOptions.define ?? {}),
				__MC_GOOGLE_CLIENT_ID_XOR__: JSON.stringify(id ? xorEncode(id, key) : []),
				__MC_GOOGLE_CLIENT_SECRET_XOR__: JSON.stringify(secret ? xorEncode(secret, key) : []),
				__MC_GOOGLE_XOR_KEY__: JSON.stringify(key),
			};
		},
	};
}
// -----------------------------------------------------------------------------

const context = await esbuild.context({
	plugins: [credentialsPlugin()],
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		__MC_BUILD__: JSON.stringify(buildInfo),
	},
});

if (prod) {
	await context.rebuild();
	copyFvadWasm();
	process.exit(0);
} else {
	copyFvadWasm();
	await context.watch();
}
